version: 2

sources:
  - name: eth
    description: here is my ETH source
    quoting:
      database: true
      schema: true
    database: ETH
    schema: ETH_SCHEMA

    tables:
      - name: contracts
        description: this is my contracts table
      - name: token_transfers
      - name: transactions
      - name: contracts_clone
        columns:
          - name: hash
            data_tests:
              - unique
